baseURL = "https://navn-r.github.io/notes"
languageCode = "en-us"
title = "<✏️ />"
theme = 'book'

publishDir = "docs"

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[menu]
[[menu.after]]
name = "Github Repo"
  url = "https://github.com/navn-r/notes"
  weight = 10

[params]
 BookSection = '*'
