baseURL = "https://navn.me/notes"
languageCode = "en-us"
title = "Notes"
theme = 'book'

publishDir = "docs"

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[menu]
[[menu.after]]
name = "Github Repo"
  url = "https://github.com/navn-r/notes"
  weight = 10

[params]
 BookSection = '*'
 BookRepo = 'https://github.com/navn-r/notes'
 BookCommitPath = 'commit'
 BookSearch = true
 BookLogo = 'logo.svg'
 BookDateFormat = "January 2, 2006"
